version: 0.2

env:
  parameter-store:
   DOCKER_REGISTRY_USERNAME: /myapp/docker-credentails/username
   DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentails/password
   DOCKER_REGISTRY_URL: /myapp/docker-credentails/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - echo "Running Tests"
      - cd simple-python-app
      - echo "Bulding Docker Image"
      - echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY_URL -u $DOCKER_REGISTRY_USERNAME --password-stdin
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest .
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest
  post_build:
    commands:
      - echo "build is successful "
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
